### ISSUE TITLE
Allow customization of the tag used for resources grouping

### ISSUE THREAD

**Issue by erikhromek** [Endava/awsimporter-impactframework-plugin#5]
The plugin currently searches for resources that have the tag **Project** on them and the value specified in the `tag` input variable, like this:

```
global-config:
        aws-importer:
          tag: 'GreenSoftware'
```

This will lookup for resources that have **GreenSoftware** value in `Project` tag.

It would be nice if you could set custom values for the tag name (not the value) because `Project` tag might be used for other purposes.

Result could be something similar to this:

```
global-config:
        aws-importer:
          tag-name: 'AWS-Importer'
          tag: 'GreenSoftware'
```

Then, `Project` tag could be used for other things.

May it be a good addition? I could try to implement this later.
